'spark.driver.memory'                               : '8G'
'spark.driver.maxResultSize'                        : '8G'
'spark.executor.cores'                              : '4'
'spark.executor.memory'                             : '8G'
'spark.yarn.queue'                                  : 'ad_hoc_group'
'spark.sql.warehouse.dir'                           : '/apps/hive/warehouse'
'spark.shuffle.service.enabled'                     : 'true'
'spark.dynamicAllocation.enabled'                   : 'true'
'spark.dynamicAllocation.maxExecutors'              : '50'
'spark.dynamicAllocation.cachedExecutorIdleTimeout' : '1200s'
'spark.yarn.dist.archives'                          : 'hdfs:///share/lib/python/conda-3.6.zip'
'spark.sql.execution.pandas.respectSessionTimeZone' : 'false'
'spark.ui.port'                                     : '4257'
'spark.driver.allowMultipleContexts'                : 'true'
'spark.port.maxRetries'                             : '64'
